### PR TITLE
enhancements: account for subworkflows and timezone

### PR DESCRIPTION
**Pull request by letaylor**
@dinvlad thanks for sharing this useful script. 

I ran into a few issues when running this. This pull request fixes the below issues:
1. Error when datetime includes timezone
2. Error when subworkflow is executed

Cheers!

### CODE REVIEW

**Comment by dinvlad** [comment]
That’s awesome, thanks! We actually deployed a different version of this script (with fixes applied) as part of the new `monitoring_image` option for Google PAPIv2 (that image has another issue atm though). I totally forgot to update it here :-)

**Comment by dinvlad** [comment]
Btw, this relies on the undocumented price list, which may change (and has changed) in format without notice, and doesn’t come with an SLA. Google now has [Billing Catalog API](https://cloud.google.com/billing/v1/how-tos/catalog-api), which is more reliable (however, I find it somewhat harder to use).

**Comment by letaylor** [comment]
Thanks Denis! The `monitoring_image` is brilliant. Thanks for pointing me to that.

**Comment by dinvlad** [comment]
It currently has an issue with reporting the very latest time point - if 2 are reported within < 1 minute, Stackdriver API started returning errors recently, and that breaks the task. I have a fix in `quay.io/dinvlad/cromwell-monitor`, just haven't made it to `quay.io/broadinstitute/cromwell-monitor `yet. But you can also use any other image you like.

**Pull request merged**
